services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8082:8080" # Macの8080ポートをコンテナの8080に繋ぐ
    depends_on:
      db:
        condition: service_started # DBが健康になってから起動
      redis:
        condition: service_started

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
